version: "3.9"

services:
  web:
    build: .
    command: python karma_shop/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"