# Generated by Django 2.2.16 on 2021-02-01 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20210201_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='home_town',
            field=models.CharField(blank=True, max_length=32, verbose_name='user home town'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 19, 0, 3, 611700, tzinfo=utc)),
        ),
    ]
