# Generated by Django 2.2.16 on 2020-11-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201105_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealsOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='product name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='product name')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='product image')),
            ],
        ),
        migrations.CreateModel(
            name='HotOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='product title')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='product description')),
                ('image', models.ImageField(blank=True, upload_to='hot_offers_images')),
            ],
        ),
    ]
