# Generated by Django 2.2.16 on 2020-11-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_singlefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlefeature',
            name='short_desc',
            field=models.CharField(blank=True, max_length=64, verbose_name='feature short description'),
        ),
        migrations.AlterField(
            model_name='singlefeature',
            name='description',
            field=models.TextField(blank=True, max_length=120, verbose_name='feature description'),
        ),
    ]
