# Generated by Django 2.2.16 on 2020-11-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='image name')),
                ('image', models.ImageField(blank=True, upload_to='auth_page_images')),
            ],
        ),
    ]
