# Generated by Django 2.2.16 on 2020-11-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authpageimages',
            name='description',
            field=models.TextField(blank=True, verbose_name='image description'),
        ),
        migrations.AddField(
            model_name='authpageimages',
            name='title',
            field=models.CharField(blank=True, max_length=64, verbose_name='image title'),
        ),
        migrations.AlterField(
            model_name='authpageimages',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='image name'),
        ),
    ]
