# Generated by Django 2.2.16 on 2020-11-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20201120_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authpageimages',
            name='description',
        ),
        migrations.RemoveField(
            model_name='authpageimages',
            name='title',
        ),
    ]
