# Generated by Django 2.2.16 on 2021-01-25 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210125_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is user verified'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 18, 23, 25, 711499, tzinfo=utc)),
        ),
    ]
