# Generated by Django 2.2.16 on 2020-11-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='feature name')),
                ('description', models.TextField(blank=True, max_length='120', verbose_name='feature description')),
                ('image', models.ImageField(blank=True, upload_to='single_feature_images')),
            ],
        ),
    ]
